version: '2'
services:
  app:
    container_name: express-example
    restart: 'no'
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./app/public:/usr/src/express-example/public
      - ./app/src:/usr/src/express-example/src
      - ./app/package.json:/usr/src/express-example/package.json
      - ./app/webpack.config.js:/usr/src/express-example/webpack.config.js
      - ./app/nodemon.json:/usr/src/express-example/nodemon.json
    links:
      - mongo
  mongo:
    container_name: mymongo
    image: mongo
    volumes:
      - ~/docker/mongodb/data:/data/db
    ports:
      - 27017:27017
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo
